version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  Build:
    executor: android/android
    steps:
      - checkout
      #      - restore_cache:
      #          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Build
          command: ./gradlew clean --warning-mode=all build
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  Test:
    executor: android/android
    steps:
      - checkout
      #      - restore_cache:
      #          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint app:test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

  Code Coverage:
    executor: android/android
    steps:
      - checkout
      #      - restore_cache:
      #          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Code Coverage
          command: ./gradlew clean debugCodeCoverage
      - store_artifacts:
          path: app/build/app_code_coverage/debugCodeCoverage/html
          destination: coverage

workflows:
  version: 2.1
  Build | Test | Code Coverage:
    jobs:
      - Build
      - Test
      - Code Coverage